import unittest

from numeralru import numeralize, Gender, Case


class TestIntToText(unittest.TestCase):

    def util_test_gender_animate_immutable_nums(self, test_data):
        for num_arr in test_data:
            n, *cases = num_arr
            for gender in [Gender.masculine, Gender.feminine, Gender.neuter]:
                for case, word in enumerate(cases):
                    for animate in [True, False]:
                        self.assertEqual(word, numeralize(n, gender, case, animate))

    def util_full_test_nums(self, test_data):
        for arr in test_data:
            n, *gender_data = arr
            for arr in gender_data:
                gender, *case_data = arr
                for arr in case_data:
                    case, *animate_data = arr
                    for animate, cor_spelling in animate_data:
                        self.assertEqual(cor_spelling,
                                         numeralize(n, gender, case, animate))

    def test_1_to_19(self):
        test_data = [
        [1,
            [Gender.masculine,
                [Case.nominative, [True, 'один'], [False, 'один']],
                [Case.genitive, [True, 'одного'], [False, 'одного']],
                [Case.dative, [True, 'одному'], [False, 'одному']],
                [Case.accusative, [True, 'одного'], [False, 'один']],
                [Case.instrumental, [True, 'одним'], [False, 'одним']],
                [Case.prepositional, [True, 'одном'], [False, 'одном']]],
            [Gender.feminine,
                [Case.nominative, [True, 'одна'], [False, 'одна']],
                [Case.genitive, [True, 'одной'], [False, 'одной']],
                [Case.dative, [True, 'одной'], [False, 'одной']],
                [Case.accusative, [True, 'одну'], [False, 'одну']],
                [Case.instrumental, [True, 'одной'], [False, 'одной']],
                [Case.prepositional, [True, 'одной'], [False, 'одной']]],
            [Gender.neuter,
                [Case.nominative, [True, 'одно'], [False, 'одно']],
                [Case.genitive, [True, 'одного'], [False, 'одного']],
                [Case.dative, [True, 'одному'], [False, 'одному']],
                [Case.accusative, [True, 'одно'], [False, 'одно']],
                [Case.instrumental, [True, 'одним'], [False, 'одним']],
                [Case.prepositional, [True, 'одном'], [False, 'одном']]]],
        [2,
            [Gender.masculine,
                [Case.nominative, [True, 'два'], [False, 'два']],
                [Case.genitive, [True, 'двух'], [False, 'двух']],
                [Case.dative, [True, 'двум'], [False, 'двум']],
                [Case.accusative, [True, 'двух'], [False, 'два']],
                [Case.instrumental, [True, 'двумя'], [False, 'двумя']],
                [Case.prepositional, [True, 'двух'], [False, 'двух']]],
            [Gender.feminine,
                [Case.nominative, [True, 'две'], [False, 'две']],
                [Case.genitive, [True, 'двух'], [False, 'двух']],
                [Case.dative, [True, 'двум'], [False, 'двум']],
                [Case.accusative, [True, 'двух'], [False, 'две']],
                [Case.instrumental, [True, 'двумя'], [False, 'двумя']],
                [Case.prepositional, [True, 'двух'], [False, 'двух']]],
            [Gender.neuter,
                [Case.nominative, [True, 'два'], [False, 'два']],
                [Case.genitive, [True, 'двух'], [False, 'двух']],
                [Case.dative, [True, 'двум'], [False, 'двум']],
                [Case.accusative, [True, 'два'], [False, 'два']],
                [Case.instrumental, [True, 'двумя'], [False, 'двумя']],
                [Case.prepositional, [True, 'двух'], [False, 'двух']]]],
        [3,
            [Gender.masculine,
                [Case.nominative, [True, 'три'], [False, 'три']],
                [Case.genitive, [True, 'трёх'], [False, 'трёх']],
                [Case.dative, [True, 'трём'], [False, 'трём']],
                [Case.accusative, [True, 'трёх'], [False, 'три']],
                [Case.instrumental, [True, 'тремя'], [False, 'тремя']],
                [Case.prepositional, [True, 'трёх'], [False, 'трёх']]],
            [Gender.feminine,
                [Case.nominative, [True, 'три'], [False, 'три']],
                [Case.genitive, [True, 'трёх'], [False, 'трёх']],
                [Case.dative, [True, 'трём'], [False, 'трём']],
                [Case.accusative, [True, 'трёх'], [False, 'три']],
                [Case.instrumental, [True, 'тремя'], [False, 'тремя']],
                [Case.prepositional, [True, 'трёх'], [False, 'трёх']]],
            [Gender.neuter,
                [Case.nominative, [True, 'три'], [False, 'три']],
                [Case.genitive, [True, 'трёх'], [False, 'трёх']],
                [Case.dative, [True, 'трём'], [False, 'трём']],
                [Case.accusative, [True, 'три'], [False, 'три']],
                [Case.instrumental, [True, 'тремя'], [False, 'тремя']],
                [Case.prepositional, [True, 'трёх'], [False, 'трёх']]]],
        [4,
            [Gender.masculine,
                [Case.nominative, [True, 'четыре'], [False, 'четыре']],
                [Case.genitive, [True, 'четырёх'], [False, 'четырёх']],
                [Case.dative, [True, 'четырём'], [False, 'четырём']],
                [Case.accusative, [True, 'четырёх'], [False, 'четыре']],
                [Case.instrumental,
                    [True, 'четырьмя'],
                    [False, 'четырьмя']],
                [Case.prepositional,
                    [True, 'четырёх'],
                    [False, 'четырёх']]],
            [Gender.feminine,
                [Case.nominative, [True, 'четыре'], [False, 'четыре']],
                [Case.genitive, [True, 'четырёх'], [False, 'четырёх']],
                [Case.dative, [True, 'четырём'], [False, 'четырём']],
                [Case.accusative, [True, 'четырёх'], [False, 'четыре']],
                [Case.instrumental,
                    [True, 'четырьмя'],
                    [False, 'четырьмя']],
                [Case.prepositional,
                    [True, 'четырёх'],
                    [False, 'четырёх']]],
            [Gender.neuter,
                [Case.nominative, [True, 'четыре'], [False, 'четыре']],
                [Case.genitive, [True, 'четырёх'], [False, 'четырёх']],
                [Case.dative, [True, 'четырём'], [False, 'четырём']],
                [Case.accusative, [True, 'четыре'], [False, 'четыре']],
                [Case.instrumental,
                    [True, 'четырьмя'],
                    [False, 'четырьмя']],
                [Case.prepositional,
                    [True, 'четырёх'],
                    [False, 'четырёх']]]],
        [5,
            [Gender.masculine,
                [Case.nominative, [True, 'пять'], [False, 'пять']],
                [Case.genitive, [True, 'пяти'], [False, 'пяти']],
                [Case.dative, [True, 'пяти'], [False, 'пяти']],
                [Case.accusative, [True, 'пять'], [False, 'пять']],
                [Case.instrumental, [True, 'пятью'], [False, 'пятью']],
                [Case.prepositional, [True, 'пяти'], [False, 'пяти']]],
            [Gender.feminine,
                [Case.nominative, [True, 'пять'], [False, 'пять']],
                [Case.genitive, [True, 'пяти'], [False, 'пяти']],
                [Case.dative, [True, 'пяти'], [False, 'пяти']],
                [Case.accusative, [True, 'пять'], [False, 'пять']],
                [Case.instrumental, [True, 'пятью'], [False, 'пятью']],
                [Case.prepositional, [True, 'пяти'], [False, 'пяти']]],
            [Gender.neuter,
                [Case.nominative, [True, 'пять'], [False, 'пять']],
                [Case.genitive, [True, 'пяти'], [False, 'пяти']],
                [Case.dative, [True, 'пяти'], [False, 'пяти']],
                [Case.accusative, [True, 'пять'], [False, 'пять']],
                [Case.instrumental, [True, 'пятью'], [False, 'пятью']],
                [Case.prepositional, [True, 'пяти'], [False, 'пяти']]]],
        [6,
            [Gender.masculine,
                [Case.nominative, [True, 'шесть'], [False, 'шесть']],
                [Case.genitive, [True, 'шести'], [False, 'шести']],
                [Case.dative, [True, 'шести'], [False, 'шести']],
                [Case.accusative, [True, 'шесть'], [False, 'шесть']],
                [Case.instrumental, [True, 'шестью'], [False, 'шестью']],
                [Case.prepositional, [True, 'шести'], [False, 'шести']]],
            [Gender.feminine,
                [Case.nominative, [True, 'шесть'], [False, 'шесть']],
                [Case.genitive, [True, 'шести'], [False, 'шести']],
                [Case.dative, [True, 'шести'], [False, 'шести']],
                [Case.accusative, [True, 'шесть'], [False, 'шесть']],
                [Case.instrumental, [True, 'шестью'], [False, 'шестью']],
                [Case.prepositional, [True, 'шести'], [False, 'шести']]],
            [Gender.neuter,
                [Case.nominative, [True, 'шесть'], [False, 'шесть']],
                [Case.genitive, [True, 'шести'], [False, 'шести']],
                [Case.dative, [True, 'шести'], [False, 'шести']],
                [Case.accusative, [True, 'шесть'], [False, 'шесть']],
                [Case.instrumental, [True, 'шестью'], [False, 'шестью']],
                [Case.prepositional, [True, 'шести'], [False, 'шести']]]],
        [7,
            [Gender.masculine,
                [Case.nominative, [True, 'семь'], [False, 'семь']],
                [Case.genitive, [True, 'семи'], [False, 'семи']],
                [Case.dative, [True, 'семи'], [False, 'семи']],
                [Case.accusative, [True, 'семь'], [False, 'семь']],
                [Case.instrumental, [True, 'семью'], [False, 'семью']],
                [Case.prepositional, [True, 'семи'], [False, 'семи']]],
            [Gender.feminine,
                [Case.nominative, [True, 'семь'], [False, 'семь']],
                [Case.genitive, [True, 'семи'], [False, 'семи']],
                [Case.dative, [True, 'семи'], [False, 'семи']],
                [Case.accusative, [True, 'семь'], [False, 'семь']],
                [Case.instrumental, [True, 'семью'], [False, 'семью']],
                [Case.prepositional, [True, 'семи'], [False, 'семи']]],
            [Gender.neuter,
                [Case.nominative, [True, 'семь'], [False, 'семь']],
                [Case.genitive, [True, 'семи'], [False, 'семи']],
                [Case.dative, [True, 'семи'], [False, 'семи']],
                [Case.accusative, [True, 'семь'], [False, 'семь']],
                [Case.instrumental, [True, 'семью'], [False, 'семью']],
                [Case.prepositional, [True, 'семи'], [False, 'семи']]]],
        [8,
            [Gender.masculine,
                [Case.nominative, [True, 'восемь'], [False, 'восемь']],
                [Case.genitive, [True, 'восьми'], [False, 'восьми']],
                [Case.dative, [True, 'восьми'], [False, 'восьми']],
                [Case.accusative, [True, 'восемь'], [False, 'восемь']],
                [Case.instrumental,
                    [True, 'восемью'],
                    [False, 'восемью']],
                [Case.prepositional, [True, 'восьми'], [False, 'восьми']]],
            [Gender.feminine,
                [Case.nominative, [True, 'восемь'], [False, 'восемь']],
                [Case.genitive, [True, 'восьми'], [False, 'восьми']],
                [Case.dative, [True, 'восьми'], [False, 'восьми']],
                [Case.accusative, [True, 'восемь'], [False, 'восемь']],
                [Case.instrumental,
                    [True, 'восемью'],
                    [False, 'восемью']],
                [Case.prepositional, [True, 'восьми'], [False, 'восьми']]],
            [Gender.neuter,
                [Case.nominative, [True, 'восемь'], [False, 'восемь']],
                [Case.genitive, [True, 'восьми'], [False, 'восьми']],
                [Case.dative, [True, 'восьми'], [False, 'восьми']],
                [Case.accusative, [True, 'восемь'], [False, 'восемь']],
                [Case.instrumental,
                    [True, 'восемью'],
                    [False, 'восемью']],
                [Case.prepositional, [True, 'восьми'], [False, 'восьми']]]],
        [9,
            [Gender.masculine,
                [Case.nominative, [True, 'девять'], [False, 'девять']],
                [Case.genitive, [True, 'девяти'], [False, 'девяти']],
                [Case.dative, [True, 'девяти'], [False, 'девяти']],
                [Case.accusative, [True, 'девять'], [False, 'девять']],
                [Case.instrumental,
                    [True, 'девятью'],
                    [False, 'девятью']],
                [Case.prepositional, [True, 'девяти'], [False, 'девяти']]],
            [Gender.feminine,
                [Case.nominative, [True, 'девять'], [False, 'девять']],
                [Case.genitive, [True, 'девяти'], [False, 'девяти']],
                [Case.dative, [True, 'девяти'], [False, 'девяти']],
                [Case.accusative, [True, 'девять'], [False, 'девять']],
                [Case.instrumental,
                    [True, 'девятью'],
                    [False, 'девятью']],
                [Case.prepositional, [True, 'девяти'], [False, 'девяти']]],
            [Gender.neuter,
                [Case.nominative, [True, 'девять'], [False, 'девять']],
                [Case.genitive, [True, 'девяти'], [False, 'девяти']],
                [Case.dative, [True, 'девяти'], [False, 'девяти']],
                [Case.accusative, [True, 'девять'], [False, 'девять']],
                [Case.instrumental,
                    [True, 'девятью'],
                    [False, 'девятью']],
                [Case.prepositional, [True, 'девяти'], [False, 'девяти']]]],
        [10,
            [Gender.masculine,
                [Case.nominative, [True, 'десять'], [False, 'десять']],
                [Case.genitive, [True, 'десяти'], [False, 'десяти']],
                [Case.dative, [True, 'десяти'], [False, 'десяти']],
                [Case.accusative, [True, 'десять'], [False, 'десять']],
                [Case.instrumental,
                    [True, 'десятью'],
                    [False, 'десятью']],
                [Case.prepositional, [True, 'десяти'], [False, 'десяти']]],
            [Gender.feminine,
                [Case.nominative, [True, 'десять'], [False, 'десять']],
                [Case.genitive, [True, 'десяти'], [False, 'десяти']],
                [Case.dative, [True, 'десяти'], [False, 'десяти']],
                [Case.accusative, [True, 'десять'], [False, 'десять']],
                [Case.instrumental,
                    [True, 'десятью'],
                    [False, 'десятью']],
                [Case.prepositional, [True, 'десяти'], [False, 'десяти']]],
            [Gender.neuter,
                [Case.nominative, [True, 'десять'], [False, 'десять']],
                [Case.genitive, [True, 'десяти'], [False, 'десяти']],
                [Case.dative, [True, 'десяти'], [False, 'десяти']],
                [Case.accusative, [True, 'десять'], [False, 'десять']],
                [Case.instrumental,
                    [True, 'десятью'],
                    [False, 'десятью']],
                [Case.prepositional, [True, 'десяти'], [False, 'десяти']]]],
        [11,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.genitive,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.dative,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.accusative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.instrumental,
                    [True, 'одиннадцатью'],
                    [False, 'одиннадцатью']],
                [Case.prepositional,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.genitive,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.dative,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.accusative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.instrumental,
                    [True, 'одиннадцатью'],
                    [False, 'одиннадцатью']],
                [Case.prepositional,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.genitive,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.dative,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']],
                [Case.accusative,
                    [True, 'одиннадцать'],
                    [False, 'одиннадцать']],
                [Case.instrumental,
                    [True, 'одиннадцатью'],
                    [False, 'одиннадцатью']],
                [Case.prepositional,
                    [True, 'одиннадцати'],
                    [False, 'одиннадцати']]]],
        [12,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.genitive,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.dative,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.accusative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.instrumental,
                    [True, 'двенадцатью'],
                    [False, 'двенадцатью']],
                [Case.prepositional,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.genitive,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.dative,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.accusative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.instrumental,
                    [True, 'двенадцатью'],
                    [False, 'двенадцатью']],
                [Case.prepositional,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.genitive,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.dative,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']],
                [Case.accusative,
                    [True, 'двенадцать'],
                    [False, 'двенадцать']],
                [Case.instrumental,
                    [True, 'двенадцатью'],
                    [False, 'двенадцатью']],
                [Case.prepositional,
                    [True, 'двенадцати'],
                    [False, 'двенадцати']]]],
        [13,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.genitive,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.dative,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.accusative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.instrumental,
                    [True, 'тринадцатью'],
                    [False, 'тринадцатью']],
                [Case.prepositional,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.genitive,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.dative,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.accusative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.instrumental,
                    [True, 'тринадцатью'],
                    [False, 'тринадцатью']],
                [Case.prepositional,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.genitive,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.dative,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']],
                [Case.accusative,
                    [True, 'тринадцать'],
                    [False, 'тринадцать']],
                [Case.instrumental,
                    [True, 'тринадцатью'],
                    [False, 'тринадцатью']],
                [Case.prepositional,
                    [True, 'тринадцати'],
                    [False, 'тринадцати']]]],
        [14,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.genitive,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.dative,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.accusative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.instrumental,
                    [True, 'четырнадцатью'],
                    [False, 'четырнадцатью']],
                [Case.prepositional,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.genitive,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.dative,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.accusative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.instrumental,
                    [True, 'четырнадцатью'],
                    [False, 'четырнадцатью']],
                [Case.prepositional,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.genitive,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.dative,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']],
                [Case.accusative,
                    [True, 'четырнадцать'],
                    [False, 'четырнадцать']],
                [Case.instrumental,
                    [True, 'четырнадцатью'],
                    [False, 'четырнадцатью']],
                [Case.prepositional,
                    [True, 'четырнадцати'],
                    [False, 'четырнадцати']]]],
        [15,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.genitive,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.dative,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.accusative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.instrumental,
                    [True, 'пятнадцатью'],
                    [False, 'пятнадцатью']],
                [Case.prepositional,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.genitive,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.dative,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.accusative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.instrumental,
                    [True, 'пятнадцатью'],
                    [False, 'пятнадцатью']],
                [Case.prepositional,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.genitive,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.dative,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']],
                [Case.accusative,
                    [True, 'пятнадцать'],
                    [False, 'пятнадцать']],
                [Case.instrumental,
                    [True, 'пятнадцатью'],
                    [False, 'пятнадцатью']],
                [Case.prepositional,
                    [True, 'пятнадцати'],
                    [False, 'пятнадцати']]]],
        [16,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.genitive,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.dative,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.accusative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.instrumental,
                    [True, 'шестнадцатью'],
                    [False, 'шестнадцатью']],
                [Case.prepositional,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.genitive,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.dative,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.accusative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.instrumental,
                    [True, 'шестнадцатью'],
                    [False, 'шестнадцатью']],
                [Case.prepositional,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.genitive,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.dative,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']],
                [Case.accusative,
                    [True, 'шестнадцать'],
                    [False, 'шестнадцать']],
                [Case.instrumental,
                    [True, 'шестнадцатью'],
                    [False, 'шестнадцатью']],
                [Case.prepositional,
                    [True, 'шестнадцати'],
                    [False, 'шестнадцати']]]],
        [17,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.genitive,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.dative,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.accusative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.instrumental,
                    [True, 'семнадцатью'],
                    [False, 'семнадцатью']],
                [Case.prepositional,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.genitive,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.dative,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.accusative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.instrumental,
                    [True, 'семнадцатью'],
                    [False, 'семнадцатью']],
                [Case.prepositional,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.genitive,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.dative,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']],
                [Case.accusative,
                    [True, 'семнадцать'],
                    [False, 'семнадцать']],
                [Case.instrumental,
                    [True, 'семнадцатью'],
                    [False, 'семнадцатью']],
                [Case.prepositional,
                    [True, 'семнадцати'],
                    [False, 'семнадцати']]]],
        [18,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.genitive,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.dative,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.accusative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.instrumental,
                    [True, 'восемнадцатью'],
                    [False, 'восемнадцатью']],
                [Case.prepositional,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.genitive,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.dative,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.accusative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.instrumental,
                    [True, 'восемнадцатью'],
                    [False, 'восемнадцатью']],
                [Case.prepositional,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.genitive,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.dative,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']],
                [Case.accusative,
                    [True, 'восемнадцать'],
                    [False, 'восемнадцать']],
                [Case.instrumental,
                    [True, 'восемнадцатью'],
                    [False, 'восемнадцатью']],
                [Case.prepositional,
                    [True, 'восемнадцати'],
                    [False, 'восемнадцати']]]],
        [19,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.genitive,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.dative,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.accusative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.instrumental,
                    [True, 'девятнадцатью'],
                    [False, 'девятнадцатью']],
                [Case.prepositional,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']]],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.genitive,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.dative,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.accusative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.instrumental,
                    [True, 'девятнадцатью'],
                    [False, 'девятнадцатью']],
                [Case.prepositional,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']]],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.genitive,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.dative,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']],
                [Case.accusative,
                    [True, 'девятнадцать'],
                    [False, 'девятнадцать']],
                [Case.instrumental,
                    [True, 'девятнадцатью'],
                    [False, 'девятнадцатью']],
                [Case.prepositional,
                    [True, 'девятнадцати'],
                    [False, 'девятнадцати']]]]
        ]
        self.util_full_test_nums(test_data)

    def test_tens(self):
        test_data = [
            [20, 'двадцать', 'двадцати', 'двадцати', 'двадцать', 'двадцатью', 'двадцати'],
            [30, 'тридцать', 'тридцати', 'тридцати', 'тридцать', 'тридцатью', 'тридцати'],
            [40, 'сорок', 'сорока', 'сорока', 'сорок', 'сорока', 'сорока'],
            [50, 'пятьдесят', 'пятидесяти', 'пятидесяти', 'пятьдесят', 'пятьюдесятью', 'пятидесяти'],
            [60, 'шестьдесят', 'шестидесяти', 'шестидесяти', 'шестьдесят', 'шестьюдесятью', 'шестидесяти'],
            [70, 'семьдесят', 'семидесяти', 'семидесяти', 'семьдесят', 'семьюдесятью', 'семидесяти'],
            [80, 'восемьдесят', 'восьмидесяти', 'восьмидесяти', 'восемьдесят', 'восемьюдесятью', 'восьмидесяти'],
            [90, 'девяносто', 'девяноста', 'девяноста', 'девяносто', 'девяноста', 'девяноста']
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_hundreds(self):
        test_data = [
            [100, 'сто', 'ста', 'ста', 'сто', 'ста', 'ста'],
            [200, 'двести', 'двухсот', 'двумстам', 'двести', 'двумястами', 'двухстах'],
            [300, 'триста', 'трёхсот', 'трёмстам', 'триста', 'тремястами', 'трёхстах'],
            [400, 'четыреста', 'четырёхсот', 'четырёмстам', 'четыреста', 'четырьмястами', 'четырёхстах'],
            [500, 'пятьсот', 'пятисот', 'пятистам', 'пятьсот', 'пятьюстами', 'пятистах'],
            [600, 'шестьсот', 'шестисот', 'шестистам', 'шестьсот', 'шестьюстами', 'шестистах'],
            [700, 'семьсот', 'семисот', 'семистам', 'семьсот', 'семьюстами', 'семистах'],
            [800, 'восемьсот', 'восьмисот', 'восьмистам', 'восемьсот', 'восемьюстами', 'восьмистах'],
            [900, 'девятьсот', 'девятисот', 'девятистам', 'девятьсот', 'девятьюстами', 'девятистах']
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_thousands(self):
        test_data = [
            [1000, 'одна тысяча', 'одной тысячи', 'одной тысяче', 'одну тысячу', 'одной тысячей', 'одной тысяче'],
            [2000, 'две тысячи', 'двух тысяч', 'двум тысячам', 'две тысячи', 'двумя тысячами', 'двух тысячах'],
            [5000, 'пять тысяч', 'пяти тысяч', 'пяти тысячам', 'пять тысяч', 'пятью тысячами', 'пяти тысячах']
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_millions(self):
        test_data = [
            [1000000,
                'один миллион',
                'одного миллиона',
                'одному миллиону',
                'один миллион',
                'одним миллионом',
                'одном миллионе'
            ],
            [2000000,
                'два миллиона',
                'двух миллионов',
                'двум миллионам',
                'два миллиона',
                'двумя миллионами',
                'двух миллионах'
            ],
            [5000000,
                'пять миллионов',
                'пяти миллионов',
                'пяти миллионам',
                'пять миллионов',
                'пятью миллионами',
                'пяти миллионах'
            ]
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_billions(self):
        test_data = [
            [1000000000,
                'один миллиард',
                'одного миллиарда',
                'одному миллиарду',
                'один миллиард',
                'одним миллиардом',
                'одном миллиарде'
            ],
            [2000000000,
                'два миллиарда',
                'двух миллиардов',
                'двум миллиардам',
                'два миллиарда',
                'двумя миллиардами',
                'двух миллиардах'
            ],
            [5000000000,
                'пять миллиардов',
                'пяти миллиардов',
                'пяти миллиардам',
                'пять миллиардов',
                'пятью миллиардами',
                'пяти миллиардах'
            ]
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_trillions(self):
        test_data = [
            [1000000000000,
                'один триллион',
                'одного триллиона',
                'одному триллиону',
                'один триллион',
                'одним триллионом',
                'одном триллионе'
            ],
            [2000000000000,
                'два триллиона',
                'двух триллионов',
                'двум триллионам',
                'два триллиона',
                'двумя триллионами',
                'двух триллионах'
            ],
            [5000000000000,
                'пять триллионов',
                'пяти триллионов',
                'пяти триллионам',
                'пять триллионов',
                'пятью триллионами',
                'пяти триллионах'
            ]
        ]
        self.util_test_gender_animate_immutable_nums(test_data)

    def test_misc_numbers(self):
        test_data = [
        [5122981121,
            [Gender.masculine,
                [Case.nominative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один']
                ],
                [Case.genitive,
                    [True, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
                    [False, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
                ],
                [Case.dative,
                    [True, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
                    [False, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
                ],
                [Case.accusative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одного'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать один']
                ],
                [Case.instrumental,
                    [True, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
                    [False, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
                ],
                [Case.prepositional,
                    [True, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
                    [False, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
                ]
            ],
            [Gender.feminine,
                [Case.nominative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна']
                ],
                [Case.genitive,
                    [True, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной'],
                    [False, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной']
                ],
                [Case.dative,
                    [True, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной'],
                    [False, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной']
                ],
                [Case.accusative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну']
                ],
                [Case.instrumental,
                    [True, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной'],
                    [False, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной']
                ],
                [Case.prepositional,
                    [True, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной'],
                    [False, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной']
                ]
            ],
            [Gender.neuter,
                [Case.nominative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно']
                ],
                [Case.genitive,
                    [True, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
                    [False, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
                ],
                [Case.dative,
                    [True, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
                    [False, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
                ],
                [Case.accusative,
                    [True, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно'],
                    [False, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно']
                ],
                [Case.instrumental,
                    [True, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
                    [False, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
                ],
                [Case.prepositional,
                    [True, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
                    [False, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
                ]],
            ]
        ]
        self.util_full_test_nums(test_data)


if __name__ == '__main__':
    unittest.main()
